// Generated by CoffeeScript 1.6.2
(function() {
  var Loot, LootFactory, factory, loot;

  Loot = (function() {
    function Loot(id, description, quantity) {
      this.id = id;
      this.description = description;
      this.quantity = quantity;
    }

    return Loot;

  })();

  LootFactory = (function() {
    var templates;

    function LootFactory() {}

    templates = ["one", "two"];

    LootFactory.prototype.create = function() {
      return new Loot(0, "phat loot", 1);
    };

    return LootFactory;

  })();

  factory = new LootFactory();

  loot = factory.create();

  console.log(loot.description);

}).call(this);

/*
//@ sourceMappingURL=lootfactory.map
*/
