// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, port;

  express = require('express');

  app = express();

  app.use(require('connect-assets')());

  app.use('/', express["static"](__dirname + '/public'));

  app.use('/lib', express["static"](__dirname + '/bower_components'));

  app.use('/src', express["static"](__dirname + '/src'));

  port = process.env.PORT || 1337;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
