// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, port;

  express = require('express');

  app = express();

  app.use(require('connect-assets')());

  app.use('/', express["static"](__dirname + '/public'));

  app.use('/lib', express["static"](__dirname + '/bower_components'));

  app.use('/src', express["static"](__dirname + '/src'));

  app.get('/ver', function(req, res) {
    return res.send(process.version);
  });

  port = process.env.PORT || 1337;

  app.listen(port, function() {
    console.log("Node v" + process.version);
    return console.log("Listening on " + port);
  });

}).call(this);
